/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RFC;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Len
 */
public class PanelBuscadorRFC extends javax.swing.JPanel {
    private String subtitulo,titulo,RFC;
    /**
     * Creates new form PanelBuscadorRFC
     */
    public PanelBuscadorRFC() {
        initComponents();
        titulo = lblTitulo.getText();
        subtitulo = txtRFC.getText();
        RFC = txtRFC.getText();
    }
    
    

    public String getSubtitulo() {
        subtitulo = txtRFC.getText();
        return subtitulo;
    }

    public void setSubtitulo(String subtitulo) {
        txtRFC.setText(subtitulo);
        this.subtitulo = subtitulo;
    }

    public String getTitulo() {
        titulo = lblTitulo.getText();
        return titulo;
    }

    public void setTitulo(String titulo) {
          lblTitulo.setText(titulo);
        this.titulo = titulo;
    }

    public String getRFC() {
        RFC = txtRFC.getText();
        return RFC;
    }

    public void setRFC(String RFC) {
          txtRFC.setText(RFC);
        this.RFC = RFC;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoRFC = new javax.swing.JDialog();
        panel1 = new RFC.Panel();
        btnBuscar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();

        javax.swing.GroupLayout DialogoRFCLayout = new javax.swing.GroupLayout(DialogoRFC.getContentPane());
        DialogoRFC.getContentPane().setLayout(DialogoRFCLayout);
        DialogoRFCLayout.setHorizontalGroup(
            DialogoRFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DialogoRFCLayout.setVerticalGroup(
            DialogoRFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnBuscar.setText("Buscar ");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        lblTitulo.setText("Información de RFC");

        txtRFC.setForeground(java.awt.Color.gray);
        txtRFC.setText("Ingrese su RFC");
        txtRFC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRFCFocusLost(evt);
            }
        });
        txtRFC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRFCMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtRFCMousePressed(evt);
            }
        });
        txtRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRFCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(26, 26, 26)
                        .addComponent(btnCrear))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnCrear))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFCActionPerformed

    private void txtRFCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRFCMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFCMouseClicked

    private void txtRFCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRFCMousePressed
    if(txtRFC.getText().equals(subtitulo)){
        txtRFC.setText("");
        txtRFC.setForeground(Color.black);
    }  
    // TODO add your handling code here:
    }//GEN-LAST:event_txtRFCMousePressed

    private void txtRFCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRFCFocusLost
     if(txtRFC.getText().isEmpty()){
    txtRFC.setText(subtitulo);
        txtRFC.setForeground(Color.gray);
    } // TODO add your handling code here:
    }//GEN-LAST:event_txtRFCFocusLost

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
    String rfcBuscado = txtRFC.getText();
    
    // Obtener la ruta del archivo desde la clase Archivo
     String ruta = "C:\\Users\\Len\\Documents\\RFC\\src\\RFC";
    String nombreArchivo = "datos.txt";
    
    try {
        BufferedReader reader = new BufferedReader(new FileReader(ruta + "\\" + nombreArchivo));
        String linea;
        boolean encontrado = false;
        while ((linea = reader.readLine()) != null) {
            if (linea.contains(rfcBuscado)) {
                encontrado = true;
                break;
            }
        }
        reader.close();
        
        if (encontrado) {
            JOptionPane.showMessageDialog(this, "El RFC está registrado.");
        } else {
            JOptionPane.showMessageDialog(this, "El RFC no está registrado.");
        }
    } catch (IOException e) {
        System.err.println("Error al leer el archivo: " + e.getMessage());
    }  // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
       DialogoRFC.pack();
    DialogoRFC.setLocationRelativeTo(this);
    DialogoRFC.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogoRFC;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel lblTitulo;
    private RFC.Panel panel1;
    private javax.swing.JTextField txtRFC;
    // End of variables declaration//GEN-END:variables
}
